---
- name: http
  package:
    name: httpie
    state: latest
- name: install HAProxy
  yum:
    name: haproxy 
    stat: latest
- name: enable HAProxy
  service:
    name: haproxy
    state: started
- name: configure haproxy
  template:
    src: ./haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
- name: restart HAproxy
  service:
    name: haproxy
    state: restarted
- name: deploy tomcat
    hosts: apps
    gather_facts: false
    become: true